server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: fz-picture-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fz-picture
    username: root
    password: 123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete #字段名
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0 #未删除

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.fangz.picture.controller