server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: fz-picture-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://--:3306/fz-picture?useSSL=false
    username: root
    password: 123456
  redis:
    host: --
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        enabled: true # 启用连接池
        max-active: 8 # 最大连接数
        max-idle: 8   # 最大空闲连接数
        min-idle: 0   # 最小空闲连接数
        max-wait: -1ms # 最大等待时间（-1 表示无限等待）

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete #字段名
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0 #未删除

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.fangz.picture.controller

# jwt配置
jwt:
  secret-key: --
  request-expiration-time: 600000 # 10分钟（单位：毫秒）
  refresh-expiration-time: 1296000000 # 15天（单位：毫秒）
  token-prefix: FzPicture
  header-string: Authorization
